; =======================================================================
; primordial_engine.asm
; PHASR Primordial Sin - Fully Unrolled Boot Attestation Engine
; Platform: Windows x86-64 (MASM ml64.exe)
; AUTO-GENERATED by generate_primordial_asm.js - DO NOT EDIT MANUALLY
; =======================================================================
;
; Unrolled Boot Byte Attestation Procedures: 4096
; Unrolled Shannon Entropy Bin Procedures:   256
; Unrolled Wave Field Seeder Procedures:     200
; Total Unrolled Procedures:                 4552
;
; Security Rationale:
;   Every boot memory byte position is validated by its own dedicated
;   procedure. This guarantees constant-time, branchless execution per
;   position, preventing timing side-channels from leaking information
;   about which byte positions differ from the trusted baseline.
;   Each procedure occupies its own branch prediction history entry,
;   eliminating cross-position microarchitectural interference.
; =======================================================================

.code

INCLUDE primordial_engine_chunk_00.asm
INCLUDE primordial_engine_chunk_01.asm
INCLUDE primordial_engine_chunk_02.asm
INCLUDE primordial_engine_chunk_03.asm
INCLUDE primordial_engine_chunk_04.asm
INCLUDE primordial_engine_chunk_05.asm
INCLUDE primordial_engine_chunk_06.asm
INCLUDE primordial_engine_chunk_07.asm
INCLUDE primordial_engine_chunk_08.asm
INCLUDE primordial_engine_chunk_09.asm
END

