# =======================================================================
# primordial_engine_linux_x64.s
# PHASR Primordial Sin - Fully Unrolled Boot Attestation Engine
# Platform: Linux x86-64 (GAS Intel Syntax)
# AUTO-GENERATED by generate_primordial_asm.js - DO NOT EDIT MANUALLY
# =======================================================================
#
# Unrolled Boot Byte Attestation Procedures: 4096
# Unrolled Shannon Entropy Bin Procedures:   256
# Unrolled Wave Field Seeder Procedures:     200
# Total Unrolled Procedures:                 4552
# =======================================================================
.intel_syntax noprefix
.text

# ============================================
# Boot Byte Attestation - Position 0
# Constant-time branchless validation
# of boot_data[0] against baseline[0]
# ============================================
# RDI = boot_data, RSI = baseline_data
# RDX = hash_accum ptr, RCX = histogram ptr
# Returns: EAX = 1 (match) or 0 (mismatch)
.include "primordial_engine_linux_x64_chunk_00.s"
.include "primordial_engine_linux_x64_chunk_01.s"
.include "primordial_engine_linux_x64_chunk_02.s"
.include "primordial_engine_linux_x64_chunk_03.s"
.include "primordial_engine_linux_x64_chunk_04.s"
.include "primordial_engine_linux_x64_chunk_05.s"
.include "primordial_engine_linux_x64_chunk_06.s"
.include "primordial_engine_linux_x64_chunk_07.s"
.include "primordial_engine_linux_x64_chunk_08.s"
.include "primordial_engine_linux_x64_chunk_09.s"

